language: elixir
sudo: false
elixir:
  - 1.5
  - 1.6
otp_release:
  - 20.0
notifications:
  email:
    on_success: change
    on_failure: change
cache:
  directories:
    - ~/.mix
    - ~/.hex
jobs:
  include:
    - stage: format
      script: mix format --check-formatted
      elixir: 1.6
    - stage: inch-ci
      env:
        - MIX_ENV=docs
      script: mix inch.report
      elixir: 1.6
