language: elixir
sudo: false
elixir:
  - 1.5
  - 1.6
otp_release:
  - 20.0
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
notifications:
  email:
    on_success: change
    on_failure: change
